name: TapTalk
description: "WhatsApp/Instagram tarzı mesajlaşma uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  intl: ^0.18.1 
  provider: ^6.1.2
  get_it: ^8.2.0
  photo_view: ^0.14.0
  emoji_picker_flutter: ^1.6.2
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.1.0
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # DEV DEPENDENCIES'E TAŞI

# APP ICON AYARLARI
flutter_icons:
  android: true
  ios: true
  image_path: "uygresim.jpg"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  android_foreground: "uygresim.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "uygresinm.jpg"

flutter:
  uses-material-design: true
  
  # Assets ekle
  assets:
   # - assets/icon/uygresim.jpg
    - assets/images/uygresinm.jpg
  
  # Material Icons fontu zaten var, bu satırı sildim
  
  # Buraya diğer asset'leri ekleyebilirsin:
  # assets:
  #   - images/
  #   - icons/